runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  runtime_version: "3.9"
  operating_system: ubuntu18

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 80