#runtime: python311
#
#entrypoint: gunicorn -b :$PORT app:app
#
#env_variables:
#  PORT: 8080

runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 80

readiness_check:
  path: "/readiness_check"
  timeout_sec: 10
  check_interval_sec: 100
  failure_threshold: 2
  success_threshold: 2


