{
  "pythonPackages": [
    {
      "repository": "https://asia-east2-python.pkg.dev/florascope/asia.gcr.io",
      "paths": ["dist/*"]
    }
  ],
  "steps": [
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": [
        "build",
        "-t",
        "asia-east2-docker.pkg.dev/florascope/my-docker-repo/myimage",
        "."
      ]
    },
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": [
        "push",
        "asia-east2-docker.pkg.dev/florascope/my-docker-repo/myimage"
      ]
    },
    {
      "name": "gcr.io/google.com/cloudsdktool/cloud-sdk",
      "entrypoint": "gcloud",
      "timeout": "240s",
      "args": [
        "compute",
        "instances",
        "create-with-container",
        "my-vm-name",
        "--container-image",
        "asia-east2-docker.pkg.dev/florascope/my-docker-repo/myimage"
      ]
    },
    {
      "name": "python",
      "entrypoint": "python",
      "args": [
        "-m",
        "pip",
        "install",
        "--upgrade",
        "pip"
      ]
    },
    {
      "name": "python",
      "entrypoint": "python",
      "args": [
        "-m",
        "pip",
        "install",
        "build",
        "pytest",
        "Flask",
        "--user"
      ]
    },
    {
      "name": "python",
      "entrypoint": "python",
      "args": [
        "-m",
        "build"
      ],
      "env": [
        "CLOUDSDK_COMPUTE_REGION=asia-east2",
        "CLOUDSDK_COMPUTE_ZONE=asia-east2-a"
      ]
    }
  ]
}
